name: Signed Releases

on:
  release:
    types: [ created ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - id: 'signs-release-artifacts'
        env:
          ZIPBALL_URL: ${{ github.event.release.zipball_url }}
          TARBALL_URL: ${{ github.event.release.tarball_url }}
          FILE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}
        run: |
          echo $ZIPBALL_URL
          echo $TARBALL_URL
          echo $FILE_NAME
          echo $UPLOAD_URL
