name: Test

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2
      - id: 'signs release artifacts'
        env:
          ZIPBALL_URL: https://api.github.com/repos/tiagoangelozup/signed-releases-demo/zipball/v0.0.1
          TARBALL_URL: https://api.github.com/repos/tiagoangelozup/signed-releases-demo/tarball/v0.0.1
          REPOSITORY_NAME: signed-releases-demo
        run: |
          curl -L "${ZIPBALL_URL}" --output "${REPOSITORY_NAME}-0.0.1.zip"
