name: Test

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ZIPBALL_URL: ${{ github.event.release.zipball_url }}
      TARBALL_URL: ${{ github.event.release.tarball_url }}

    steps:
      - run: |
          echo $ZIPBALL_URL
          echo $TARBALL_URL
