name: Test

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2
      - env:
          ZIPBALL_URL: ${{ github.event.release.zipball_url }}
          TARBALL_URL: ${{ github.event.release.tarball_url }}
          REF: ${{ github.event.ref }}
        run: |
          echo $ZIPBALL_URL
          echo $TARBALL_URL
          echo $REF
